theme: minima
minima: 
  include_nav: true
nav: 
  - title: "Home"
    url: "/"
  - title: "A2"
    url: "/Assignment2/" 
  - title: "A3"
    url: "/Assignment3/"
  - title: "A4"
    url: "/Assignment4/"
  - title: "Hackathon"
    url: "/Hackathon/"  
title: Project group - Data Analysis 1
description: This is our personal website created to show our project.
